# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    working_directory: ~/website_dev/
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "8d:db:8f:f7:49:dd:c0:ed:20:35:3c:1a:69:2c:5c:85"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete ./ ${USER_NAME}@${HOST_NAME}:~/nginx/
            fi
