# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    working_directory: ~/website_dev/
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "e9:d4:53:08:97:4c:a6:cf:10:0a:9a:3d:b3:04:df:e6"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:~/nginx/
            fi
