# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    working_directory: ~/website_dev/
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "57:f9:b3:14:1f:46:52:82:c1:9e:6c:f3:ce:73:3a:05"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}: ./nginx/
            fi
